name: Deploy to GitHub Pages

on:
  release:
    types: [created]
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Prepare deployment
        id: prepare
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Build deployment directory
        run: |
          TAG="${{ steps.prepare.outputs.tag }}"
          IS_RELEASE="${{ steps.prepare.outputs.is_release }}"
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          
          mkdir -p deploy
          
          if [ "$IS_RELEASE" == "true" ]; then
            mkdir -p "deploy/${REPO_NAME}/${TAG}"
            cp -r index.html ru en "deploy/${REPO_NAME}/${TAG}/"
            
            python3 .github/scripts/generate_html.py "${REPO_NAME}" "${TAG}" "${{ github.repository }}"
          else
            cp -r index.html ru en deploy/
          fi
      
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          keep_files: true
